"""End-to-end fix for a video where the slideshow was built from PREDICTED
scene durations but the real TTS audio drifted longer.

Steps:
    1. ffprobe each narration_NN.mp3 → overwrite scene.duration_sec.
    2. Re-render video.mp4 with the real durations (no subtitle burn).
    3. Delete the stale upload on YouTube.
    4. Upload the new video with the existing metadata.json.
    5. Re-attach the already-translated caption SRTs in the run dir.
       (No re-translation — the .es/.pt/.hi/.id SRTs were regenerated by
       fix_captions.py and already match the real durations.)

Usage:
    python replace_with_real_durations.py output/2026-04-25T14-11-43 MEEaD56SuxA
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from config.settings import get_settings
from src.utils.logger import log
from src.utils.models import Scene
from src.video.ffmpeg_assembler import FFmpegAssembler
from src.youtube.uploader import (
    API_SERVICE_NAME,
    API_VERSION,
    YouTubeUploader,
)


def _ffprobe_duration(path: Path) -> float | None:
    if not path.exists() or not shutil.which("ffprobe"):
        return None
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, timeout=15,
    )
    if r.returncode != 0:
        return None
    try:
        return float(r.stdout.strip())
    except ValueError:
        return None


def main(run_dir_str: str, old_video_id: str) -> int:
    settings = get_settings()
    run_dir = Path(run_dir_str).resolve()

    scenes_json = run_dir / "scenes.json"
    narration_path = run_dir / "narration.mp3"
    metadata_path = run_dir / "metadata.json"
    src_srt = run_dir / "subtitles.srt"

    for must_exist in (scenes_json, narration_path, metadata_path, src_srt):
        if not must_exist.exists():
            log.error("missing: {}", must_exist)
            return 2

    # ---- 1) Load scenes + measure real durations -----------------------
    raw = json.loads(scenes_json.read_text(encoding="utf-8"))
    scenes = [
        Scene(
            index=s["index"],
            duration_sec=s["duration_sec"],
            narration=s["narration"],
            on_screen_text=s.get("on_screen_text", ""),
            image_prompt=s.get("image_prompt", ""),
            image_path=Path(s["image_path"]) if s.get("image_path") else None,
        )
        for s in raw
    ]

    log.info("Measuring real TTS durations...")
    total_predicted = sum(s.duration_sec for s in scenes)
    for i, scene in enumerate(scenes):
        a = run_dir / f"narration_{i:02d}.mp3"
        m = _ffprobe_duration(a)
        if m is not None:
            log.info("  scene {}: predicted={:.2f}s -> actual={:.2f}s",
                     i, scene.duration_sec, m)
            scene.duration_sec = m
    total_real = sum(s.duration_sec for s in scenes)
    log.info("Total: predicted={:.1f}s -> real={:.1f}s (drift +{:.1f}s)",
             total_predicted, total_real, total_real - total_predicted)

    # Persist updated scenes.json so future tooling agrees.
    raw_updated = []
    for s, src in zip(scenes, raw):
        out = dict(src)
        out["duration_sec"] = s.duration_sec
        raw_updated.append(out)
    scenes_json.write_text(json.dumps(raw_updated, indent=2, ensure_ascii=False),
                            encoding="utf-8")
    log.info("scenes.json updated with real durations")

    # ---- 2) Re-render video.mp4 with real durations (no burn-in) -------
    video_path = run_dir / "video.mp4"
    if video_path.exists():
        backup = video_path.with_suffix(".old55s.mp4.bak")
        try:
            video_path.replace(backup)
            log.info("Old video backed up to {}", backup.name)
        except OSError:
            pass

    log.info("Re-rendering slideshow at real {:.1f}s length...", total_real)
    assembler = FFmpegAssembler()
    assembler.assemble(
        scenes,
        video_path,
        narration_path=narration_path,
        subtitle_path=None,  # captions live as YouTube tracks now
        vertical=True,
    )
    new_dur = _ffprobe_duration(video_path)
    log.info("New video.mp4: {:.1f}s ({} bytes)",
             new_dur or -1, video_path.stat().st_size)

    # ---- 3) OAuth + delete old upload ----------------------------------
    uploader = YouTubeUploader(
        client_secrets_file=Path(settings.youtube_client_secrets_file),
        token_file=Path(settings.youtube_token_file),
    )
    creds = uploader._get_credentials()
    yt = build(API_SERVICE_NAME, API_VERSION, credentials=creds)
    uploader._client = yt

    try:
        yt.videos().delete(id=old_video_id).execute()
        log.info("Deleted old video id={}", old_video_id)
    except HttpError as exc:
        log.warning("Could not delete {}: {}", old_video_id, exc)

    # ---- 4) Upload re-render with the same metadata --------------------
    meta = json.loads(metadata_path.read_text(encoding="utf-8"))
    new_id = uploader.upload(
        video_path=video_path,
        title=meta["title"],
        description=meta["description"],
        tags=meta.get("tags", []),
        category_id=meta.get("category_id", settings.youtube_category_id),
        privacy_status=settings.youtube_privacy_status,
        made_for_kids=settings.youtube_made_for_kids,
    )

    # ---- 5) Re-attach existing caption SRTs (no re-translate) ----------
    langs = [c.strip() for c in (settings.caption_languages or "").split(",") if c.strip()]
    source_lang = langs[0] if langs else "en"

    paths: dict[str, Path] = {}
    for lang in langs:
        if lang == source_lang:
            paths[lang] = src_srt
        else:
            cand = run_dir / f"subtitles.{lang}.srt"
            if cand.exists():
                paths[lang] = cand
            else:
                log.warning("Missing translated SRT for {}, skipping", lang)

    log.info("Attaching {} caption tracks (already-translated)...", len(paths))
    uploader.upload_captions(
        video_id=new_id,
        srt_paths=paths,
        source_lang=source_lang,
    )

    log.info("DONE - replacement video: https://youtu.be/{}", new_id)
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python replace_with_real_durations.py <run_dir> <old_video_id>")
        sys.exit(1)
    sys.exit(main(sys.argv[1], sys.argv[2]))
